apiVersion: v1
kind: Service
metadata:
  name: store-sales-worker-go-ms-service
spec:
  selector:
    app: store-sales-worker-go-ms
  ports:
    - protocol: TCP
      port: 3040
      targetPort: 3040
  type: NodePort
  
